### ISSUE TITLE
Examples are too small on mobile 

### ISSUE THREAD

**Issue by kmonsoor** [mplewis/src2png#1]
As the four examples on the Readme file are side-by-side, they shows up too small on mobile device.

I can think of two ways to solve the problem.

1. Keep one example on the same place and move other three to a new section near the bottom, to section named "more examples".

2. place the example images one after another.

## screenshot 
![screenshot_20170912-055957](https://user-images.githubusercontent.com/1219418/30301970-c3ccf484-977f-11e7-884f-a3946b60475a.png)

**Comment by suchipi** [comment]
I don't think it's possible to do this kind of responsive design using markdown tables...

Luckily, you can always zoom in

**Comment by mplewis** [comment]
Thanks for the suggestion! I'm going to keep it as-is for now, because:

1. the touch targets still work OK – they're not terrible even on an iPhone 5
2. the banner image illustrates what the project does
