### ISSUE TITLE
FireShot makes this redundant

### ISSUE THREAD

**Issue by Ivanca** [mplewis/src2png#3]
The FireShot Chrome extension (and any screenshot extension that supports full page shots) makes this project redundant because you can always create a gist (ej gist.github.com) and screenshoot it instead of using this.

Example (taken with FireShot, no cropping but it has that option too):

![image](https://user-images.githubusercontent.com/907138/30307626-0c2a4654-9745-11e7-90c4-dbbdd6355965.png)

**Comment by Ivanca** [comment]
Also, it damages readability (cant be googled cause it's an image, etc); so its better just to copy the generated HTML with something like  [SnappySnippet](https://chrome.google.com/webstore/detail/snappysnippet/blfngdefapoapkcdibbdkigpeaffgcil?hl=en)

**Comment by mplewis** [comment]
Thanks for the suggestion! FireShot doesn't quite do what I want, which is capture HR images in bulk.

I generally only use images of code in Keynote presentations, so I am okay with the lack of indexability in those cases.
